language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-math --save
  - npm install hexo-generator-searchdb --save
  - npm install hexo-symbols-count-time --save
  - npm install hexo-generator-feed --save
  - npm i --save hexo-wordcount
  - npm install mermaid --save
  - npm install --save hexo-tag-mermaid
  - npm install hexo-tag-plantuml --save

before_script:
  - cd ./themes/next
  #- git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
  - git clone https://github.com/theme-next/theme-next-jquery-lazyload source/lib/jquery_lazyload
  - git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
  - git clone https://github.com/theme-next/theme-next-pace source/lib/pace
  - git clone https://github.com/theme-next/theme-next-pangu.git source/lib/pangu
  - git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress

  - cd ..
  - cd ..
script:
  - hexo -version
  - hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "tankeryang"
  - git config user.email "youngzyang@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/tankeryang/tankeryang.github.io.git