language: node_js
node_js: stable

branches:
  only:
  - dev

before_install:
# 解密私钥并设置为本机 ssh 私钥
- openssl aes-256-cbc -K $encrypted_fe7db267074f_key -iv $encrypted_fe7db267074f_iv
  -in .travis/id_rsa_gitee.enc -out ~/.ssh/id_rsa_gitee -d
- openssl aes-256-cbc -K $encrypted_fe7db267074f_key -iv $encrypted_fe7db267074f_iv
  -in .travis/travis.key.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/id_rsa_gitee
- chmod 600 ~/.ssh/travis.key
# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/config ~/.ssh/config

install:
- npm install
- npm install hexo-math --save
- npm install hexo-generator-searchdb --save
- npm install hexo-symbols-count-time --save
- npm install hexo-generator-feed --save
- npm install hexo-wordcount --save
- npm install mermaid --save
- npm install hexo-tag-mermaid --save
- npm install hexo-tag-plantuml --save

before_script:
- cd ./themes/next
- git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
- git clone https://github.com/theme-next/theme-next-jquery-lazyload source/lib/jquery_lazyload
- git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
- git clone https://github.com/theme-next/theme-next-pace source/lib/pace
- git clone https://github.com/theme-next/theme-next-pangu.git source/lib/pangu
- git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress
- cd ..
- cd ..

script:
- hexo -version
- hexo clean && hexo g

after_script:
# 先 clone 再 commit，避免直接 force commit
# 不然整个 branch 就总是只有一个 commit，不好看
- git clone -b master git@github.com:tankeryang/tankeryang.github.io.git .deploy_git
- cd .deploy_git
- git checkout master
- mv .git/ ../public/
# 提交更改
- cd ../public
- git config user.name "tankeryang"
- git config user.email "youngzyang@outlook.com"
- git add .
- git commit -m "Site updated:`date +"%Y-%m-%d %H:%M:%S"`"
# 添加coding和gitee的远程库
- git remote add coding git@git.coding.net:tankeryang/tankeryang.git
- git remote add gitee git@gitee.com:tankeryang/tankeryang.git
# push
- git push -u origin master
- git push -u coding master
- git push -u gitee master
# - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# env:
#   global:
#   - GH_REF: github.com/tankeryang/tankeryang.github.io.git

